global using System.Text;
global using System.Collections;
global using DocumentFormat.OpenXml;
global using DocumentFormat.OpenXml.Packaging;
global using A = DocumentFormat.OpenXml.Drawing;
global using P = DocumentFormat.OpenXml.Presentation;
global using D = DocumentFormat.OpenXml.Drawing;
global using DocuChef.Presentation.Core;
global using DocuChef.Presentation.Models;
global using DocuChef.Presentation.Utils;
