using System.Text.RegularExpressions;
using DocuChef.Presentation.Exceptions;
using DocuChef.Presentation.Models;
using DocuChef.Presentation.Utilities;

namespace DocuChef.Presentation.Processors;

/// <summary>
/// Analyzes PowerPoint template slides to extract binding expressions and directives
/// </summary>
public class TemplateAnalyzer
{
    // Compiled regex patterns for performance optimization
    private static readonly Regex BindingExpressionRegex = new Regex(@"\$\{([^}]+)\}", RegexOptions.Compiled);
    private static readonly Regex ArrayIndexRegex = new Regex(@"(.+?)\[(\d+)\]", RegexOptions.Compiled);
    private static readonly Regex FormatSpecifierRegex = new Regex(@"(.+?)(?::(.+))?$", RegexOptions.Compiled);
    private static readonly Regex DirectiveRegex = new Regex(@"#(foreach|range|alias)\s*:\s*(.+)", RegexOptions.Compiled | RegexOptions.IgnoreCase);
    private static readonly Regex ConditionalRegex = new Regex(@"(.+?)\s*\?\s*(.+?)\s*:\s*(.+)", RegexOptions.Compiled);
    private static readonly Regex MethodCallRegex = new Regex(@"(.+)\(\)$", RegexOptions.Compiled);
    private static readonly Regex ForeachOptionsRegex = new Regex(@"(.+?)(?:,\s*max\s*:\s*(\d+))?(?:,\s*offset\s*:\s*(\d+))?$", RegexOptions.Compiled | RegexOptions.IgnoreCase);
    private static readonly Regex RangeOptionsRegex = new Regex(@"(?:(begin|end)\s*,\s*)?(.+)", RegexOptions.Compiled | RegexOptions.IgnoreCase);
    private static readonly Regex AliasOptionsRegex = new Regex(@"(.+?)\s+as\s+(.+)", RegexOptions.Compiled | RegexOptions.IgnoreCase);
    private static readonly Regex ContextOperatorRegex = new Regex(@"(.+?)>(.+)", RegexOptions.Compiled);
    
    /// <summary>
    /// Analyzes a slide and extracts its binding expressions and directives
    /// </summary>
    /// <param name="slide">The slide object to analyze</param>
    /// <param name="slideNotes">The notes content of the slide</param>
    /// <param name="slideId">The unique identifier of the slide</param>
    /// <returns>A SlideInfo object containing analysis results</returns>
    public SlideInfo Analyze(object slide, string slideNotes, int slideId)    {
        var slideInfo = new SlideInfo
        {
            SlideId = slideId,
            Type = SlideType.Static
        };

        // Parse directives from slide notes
        if (!string.IsNullOrEmpty(slideNotes))
        {
            slideInfo.Directives = ParseSlideNotes(slideNotes);
        }

        // Extract binding expressions from slide text
        var bindingExpressions = ExtractBindingExpressions(slide);
        var expressionsToProcess = bindingExpressions.ToList(); // Make a copy to avoid modification issues
        foreach (var expressionText in expressionsToProcess)
        {
            try
            {
                var bindingExpression = ParseBindingExpression(expressionText);
                slideInfo.BindingExpressions.Add(bindingExpression);
            }
            catch (Exception)
            {
                // Skip invalid expressions but log them in debug environments
                System.Diagnostics.Debug.WriteLine($"Skipped invalid expression: {expressionText}");
            }
        }

        // If no directives are specified but there are array indices, auto-generate directives
        if (slideInfo.Directives.Count == 0 && slideInfo.BindingExpressions.Any())
        {
            AutoGenerateDirectives(slideInfo);
        }

        // Determine slide type and additional properties
        DetermineSlideProperties(slideInfo);

        return slideInfo;
    }

    /// <summary>
    /// Parses slide notes to extract directives
    /// </summary>
    /// <param name="notes">The slide notes text to parse</param>
    /// <returns>List of parsed directives</returns>
    public List<Directive> ParseSlideNotes(string notes)
    {
        var directives = new List<Directive>();
        
        // Split notes by line and process each line
        var lines = notes.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
        
        foreach (var line in lines)
        {
            var match = DirectiveRegex.Match(line.Trim());
            if (!match.Success) 
                continue;
                
            string directiveType = match.Groups[1].Value.ToLowerInvariant();
            string options = match.Groups[2].Value.Trim();
            
            try
            {
                var directive = ParseDirective(directiveType, options);
                if (directive != null)
                    directives.Add(directive);
            }
            catch (Exception)
            {
                // Skip invalid directives
            }
        }
        
        return directives;
    }

    /// <summary>
    /// Parses a specific directive based on its type and options
    /// </summary>
    /// <param name="directiveType">The type of directive (foreach, range, alias)</param>
    /// <param name="options">The directive options string</param>
    /// <returns>A parsed Directive object</returns>
    public Directive ParseDirective(string directiveType, string options)
    {
        return directiveType switch
        {
            "foreach" => ParseForeachDirective(options),
            "range" => ParseRangeDirective(options),
            "alias" => ParseAliasDirective(options),
            _ => throw new ArgumentException($"Unknown directive type: {directiveType}")
        };
    }

    /// <summary>
    /// Parses a foreach directive
    /// </summary>
    private Directive ParseForeachDirective(string options)
    {
        var match = ForeachOptionsRegex.Match(options);
        if (!match.Success)
            throw new ArgumentException($"Invalid foreach directive options: {options}");

        var directive = new Directive
        {
            Type = DirectiveType.Foreach,
            CollectionPath = match.Groups[1].Value.Trim()
        };

        if (match.Groups[2].Success && int.TryParse(match.Groups[2].Value, out int maxItems))
        {
            directive.MaxItems = maxItems;
        }

        if (match.Groups[3].Success && int.TryParse(match.Groups[3].Value, out int offset))
        {
            directive.Offset = offset;
        }

        return directive;
    }

    /// <summary>
    /// Parses a range directive
    /// </summary>
    private Directive ParseRangeDirective(string options)
    {
        var match = RangeOptionsRegex.Match(options);
        if (!match.Success)
            throw new ArgumentException($"Invalid range directive options: {options}");

        var directive = new Directive
        {
            Type = DirectiveType.Range,
            CollectionPath = match.Groups[2].Value.Trim()
        };        if (match.Groups[1].Success)
        {
            string rangeType = match.Groups[1].Value.ToLowerInvariant();
            directive.RangeBoundary = rangeType == "begin" ? RangeBoundary.Begin : RangeBoundary.End;
        }

        return directive;
    }

    /// <summary>
    /// Parses an alias directive
    /// </summary>
    private Directive ParseAliasDirective(string options)
    {
        var match = AliasOptionsRegex.Match(options);
        if (!match.Success)
            throw new ArgumentException($"Invalid alias directive options: {options}");        return new Directive
        {
            Type = DirectiveType.Alias,
            CollectionPath = match.Groups[1].Value.Trim(),
            AliasName = match.Groups[2].Value.Trim()
        };
    }    /// <summary>
    /// Extracts binding expressions from slide content
    /// </summary>
    /// <param name="slide">The slide object to extract expressions from</param>
    /// <returns>Collection of binding expression strings</returns>
    private IEnumerable<string> ExtractBindingExpressions(object slide)
    {
        // Extract text from slide using SlideTextExtractor utility
        var slideText = SlideTextExtractor.GetText(slide);
        
        // Find all binding expressions in the text
        var matches = BindingExpressionRegex.Matches(slideText);
        
        return matches.Cast<Match>()
                     .Select(m => m.Value) // Use the full match (including ${})
                     .Distinct()
                     .ToList();
    }    /// <summary>
    /// Parses a binding expression string into a BindingExpression object
    /// </summary>
    /// <param name="expressionText">The expression text to parse</param>
    /// <returns>A parsed BindingExpression object</returns>
    private BindingExpression ParseBindingExpression(string expressionText)
    {
        // Extract the inner expression from ${...}
        var innerExpression = expressionText;
        if (expressionText.StartsWith("${") && expressionText.EndsWith("}"))
        {
            innerExpression = expressionText.Substring(2, expressionText.Length - 3);
        }

        var expression = new BindingExpression
        {
            OriginalExpression = expressionText,
            DataPath = innerExpression
        };        // Parse context operator (>) 
        var contextMatch = ContextOperatorRegex.Match(innerExpression);
        if (contextMatch.Success)
        {
            expression.UsesContextOperator = true;
            // Keep the full path for context operator expressions
            // DataPath should remain as "Categories>Items[0].Name"
        }

        // Parse conditional expression (? :)
        var conditionalMatch = ConditionalRegex.Match(expression.DataPath);
        if (conditionalMatch.Success)
        {
            expression.IsConditional = true;
            expression.DataPath = conditionalMatch.Groups[1].Value.Trim();
        }

        // Parse method call
        var methodMatch = MethodCallRegex.Match(expression.DataPath);
        if (methodMatch.Success)
        {
            expression.IsMethodCall = true;
            expression.DataPath = methodMatch.Groups[1].Value.Trim();
        }

        // Parse format specifier (:format)
        var formatMatch = FormatSpecifierRegex.Match(expression.DataPath);
        if (formatMatch.Success && formatMatch.Groups[2].Success)
        {
            expression.DataPath = formatMatch.Groups[1].Value.Trim();
            expression.FormatSpecifier = formatMatch.Groups[2].Value.Trim();
        }        // Parse array indices using existing ArrayIndices dictionary
        var currentPath = expression.DataPath;
        var arrayMatch = ArrayIndexRegex.Match(currentPath);
        if (arrayMatch.Success)
        {
            string arrayPath = arrayMatch.Groups[1].Value.Trim();
            if (int.TryParse(arrayMatch.Groups[2].Value, out int index))
            {
                // Extract the array name (last part of the path before the index)
                string arrayName = arrayPath;
                if (arrayPath.Contains('.'))
                {
                    var parts = arrayPath.Split('.');
                    arrayName = parts[0]; // Use the first part as the collection name
                }
                else if (arrayPath.Contains('>'))
                {
                    var parts = arrayPath.Split('>');
                    arrayName = parts[0]; // Use the first part as the collection name
                }
                
                expression.ArrayIndices[arrayName] = index;
                // Keep the full path for data binding
                expression.DataPath = currentPath; 
            }
        }

        return expression;
    }    /// <summary>
    /// Auto-generates directives for slides with array expressions but no explicit directives
    /// </summary>
    private void AutoGenerateDirectives(SlideInfo slideInfo)
    {
        var arrayExpressions = slideInfo.BindingExpressions
            .Where(expr => expr.ArrayIndices.Any())
            .GroupBy(expr => expr.ArrayIndices.Keys.First()) // Group by collection name
            .ToList();

        foreach (var group in arrayExpressions)
        {
            var maxIndex = group.SelectMany(expr => expr.ArrayIndices.Values).Max();
            
            var directive = new Directive
            {
                Type = DirectiveType.Foreach,
                CollectionPath = group.Key,
                MaxItems = maxIndex + 1 // Convert from 0-based to count
            };
            
            slideInfo.Directives.Add(directive);
        }
    }/// <summary>
    /// Determines slide type and additional properties based on directives and expressions
    /// </summary>
    private void DetermineSlideProperties(SlideInfo slideInfo)
    {
        // Calculate max array index first
        var maxIndex = slideInfo.BindingExpressions
            .SelectMany(expr => expr.ArrayIndices.Values)
            .DefaultIfEmpty(-1)
            .Max();

        if (maxIndex >= 0)
        {
            slideInfo.MaxArrayIndex = maxIndex;
        }

        // Determine slide type
        if (slideInfo.Directives.Any(d => d.Type == DirectiveType.Range))
        {
            var rangeDirective = slideInfo.Directives.First(d => d.Type == DirectiveType.Range);
            slideInfo.Type = rangeDirective.RangeBoundary == RangeBoundary.Begin ? SlideType.Source : SlideType.Cloned;
        }
        else if (slideInfo.Directives.Any(d => d.Type == DirectiveType.Foreach) || slideInfo.HasArrayReferences)
        {
            slideInfo.Type = SlideType.Source;
        }
        else
        {
            slideInfo.Type = SlideType.Static;
        }

        // Set collection name
        var foreachDirective = slideInfo.Directives.FirstOrDefault(d => d.Type == DirectiveType.Foreach);
        if (foreachDirective != null)
        {
            slideInfo.CollectionName = foreachDirective.CollectionPath;
        }
        else if (slideInfo.HasArrayReferences)
        {
            // Get collection name from array expressions
            var arrayExpression = slideInfo.BindingExpressions.FirstOrDefault(expr => expr.ArrayIndices.Any());
            if (arrayExpression != null)
            {
                slideInfo.CollectionName = arrayExpression.ArrayIndices.Keys.First();
            }
        }
    }

    /// <summary>
    /// Gets the collection names referenced in binding expressions
    /// </summary>
    /// <param name="slideInfo">The slide info to analyze</param>
    /// <returns>Collection of unique collection names</returns>
    public IEnumerable<string> GetReferencedCollections(SlideInfo slideInfo)
    {
        var collections = new HashSet<string>();

        // Add collections from directives
        foreach (var directive in slideInfo.Directives)
        {
            if (!string.IsNullOrEmpty(directive.CollectionPath))
            {
                collections.Add(directive.CollectionPath);
            }
        }

        // Add collections from array expressions
        foreach (var expression in slideInfo.BindingExpressions)
        {
            if (expression.ArrayIndices.Any())
            {
                collections.Add(expression.DataPath);
            }
        }

        return collections;
    }

    /// <summary>
    /// Validates that a slide info object is properly structured
    /// </summary>
    /// <param name="slideInfo">The slide info to validate</param>
    /// <returns>True if valid, false otherwise</returns>
    public bool ValidateSlideInfo(SlideInfo slideInfo)
    {
        if (slideInfo == null)
            return false;

        // Validate that range directives have corresponding slides
        var rangeDirectives = slideInfo.Directives.Where(d => d.Type == DirectiveType.Range).ToList();
        if (rangeDirectives.Count > 1)
        {
            // A slide can only have one range directive
            return false;
        }

        // Validate that alias directives have valid names
        var aliasDirectives = slideInfo.Directives.Where(d => d.Type == DirectiveType.Alias).ToList();
        foreach (var alias in aliasDirectives)
        {
            if (string.IsNullOrWhiteSpace(alias.AliasName))
                return false;
        }        return true;
    }
}
